name: main
on: 
  push:
    branches: [main]
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  publish-release:
    runs-on: ubuntu-24.04-arm
    needs: ci
    concurrency:
      group: deploy-production
    environment:
      name: production
      url: https://chrisjarling.com
    steps:
      - name: release
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'

